kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  namespace: poc-demo
  labels:
    app: golang-simple-echoservice
    app.kubernetes.io/component: golang-simple-echoservice
    app.kubernetes.io/instance: golang-simple-echoservice
    name: golang-simple-echoservice
  name: golang-simple-echoservice

spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app.kubernetes.io: golang-simple-echoservice
  template:
    metadata:
      labels:
        app.kubernetes.io: golang-simple-echoservice
        name: golang-simple-echoservice
    spec:
      containers:
        - resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /api/v1/sys/info/isalive
              port: 9000
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1
          terminationMessagePath: /dev/termination-log
          name: golang-simple-echoservice
          livenessProbe:
            httpGet:
              path: /api/v1/sys/info/isalive
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 55
            timeoutSeconds: 5
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: LOG_LEVEL
              value: trace
            - name: VERSION
              value: 1.0.1
            - name: SERVER_PORT
              value: '9000'
            - name: NAME
              value: golang-simple-echoservice
          ports:
            - containerPort: 9000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: >-
            quay.io/luigizuccarelli/golang-simple-echoservice:1.15.6
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
